// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxEDIgXpCfe91OKHnOeGbFGBec7gYDGKc',
    appId: '1:758071054197:web:317d63b9434deb7b070d3c',
    messagingSenderId: '758071054197',
    projectId: 'gmail-signin-test',
    authDomain: 'signin-test-f336b.firebaseapp.com',
    storageBucket: 'gmail-signin-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEsEqKeyiPTCeN4631CDqnPy6DJl53hqo',
    appId: '1:758071054197:android:90cdeb8e88b5b9ec070d3c',
    messagingSenderId: '758071054197',
    projectId: 'gmail-signin-test',
    storageBucket: 'gmail-signin-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWJfbwsllv5RWqbXOY3cdDCeNhMMUdmgk',
    appId: '1:758071054197:ios:5f28718c1826e348070d3c',
    messagingSenderId: '758071054197',
    projectId: 'gmail-signin-test',
    storageBucket: 'gmail-signin-test.appspot.com',
    iosClientId: '758071054197-3ku8ms9esetumaasdgas05ofoecr08lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmailSignin',
  );
}
